Updated ResEdge API to be environment variable (#33)
* Updated ResEdge API to be environment variable

* Renamed variable to KIC_DATASERVICE_URL

* Added check for Environment Variable

diff --git a/labs/beta-labs/res-edge-labs/.kic/commands/check/resedge b/labs/beta-labs/res-edge-labs/.kic/commands/check/resedge
--- a/labs/beta-labs/res-edge-labs/.kic/commands/check/resedge
+++ b/labs/beta-labs/res-edge-labs/.kic/commands/check/resedge
@@ -1,7 +1,14 @@
 #!/bin/bash
 
+set -e
+
+if [ -z "${KIC_DATASERVICE_URL}" ]; then
+    echo "Error! Please set environment variable: KIC_DATASERVICE_URL";
+    exit 1;
+fi
+
 function resedge_check {
-    http localhost:32080/version
+    http "${KIC_DATASERVICE_URL}"/version
 }
 
 if ! resedge_check; then
