update overlay and readme

diff --git a/labs/beta-labs/kustomize/.kic/commands/overlay b/labs/beta-labs/kustomize/.kic/commands/overlay
--- a/labs/beta-labs/kustomize/.kic/commands/overlay
+++ b/labs/beta-labs/kustomize/.kic/commands/overlay
@@ -3,15 +3,20 @@
 set -e
 
 dir=""
+app="apps/$2"
+
+if [ "$app" = "apps/" ]; then
+    echo "app directory not found";
+    exit 1;
+fi
 
 if [ "$1" = "" ]; then
     echo "Usage: kic overlay name"
     exit 1;
 fi
 
-# change to the apps/imdb dir
-# todo - imdb shoud be a param
-if [ -d "apps/imdb" ]; then cd apps/imdb; fi
+# change to the apps/myapp dir
+cd "$app";
 
 # select the environment
 if [ -d "kustomize/dev" ]; then dir="kustomize/dev"; fi
@@ -30,21 +35,6 @@ fi
 
 mkdir -p "$dir/overlays/$1"
 
-cat <<EOF > "$dir/overlays/$1/kustomization.yaml"
-apiVersion: kustomize.config.k8s.io/v1beta1
-kind: Kustomization
-metadata:
-  annotations:
-    version: $1
-    clusters: none
-
-resources:
-- ../../base
-
-# todo - read the image name from the base yaml
-images:
-- name: ghcr.io/bartr/imdb
-  newTag: $1
-EOF
+cp "$dir/base/kustomization.yaml" "$dir/overlays/$1/kustomization.yaml"
 
 code "$dir/overlays/$1/kustomization.yaml"
