updated error handling

diff --git a/labs/beta-labs/kustomize/.kic/commands/overlay b/labs/beta-labs/kustomize/.kic/commands/overlay
--- a/labs/beta-labs/kustomize/.kic/commands/overlay
+++ b/labs/beta-labs/kustomize/.kic/commands/overlay
@@ -5,13 +5,25 @@ set -e
 dir=""
 app="apps/$1"
 
-if [ "$app" = "apps/" ]; then
-    echo "app directory not found";
+function print_usage
+{
+    echo "Usage: kic overlay <name> <version>"
+}
+
+if [ "$1" = "" ]; then
+    echo "Application name is required."
+    print_usage
     exit 1;
 fi
 
 if [ "$2" = "" ]; then
-    echo "Usage: kic overlay name"
+    echo "Version is required."
+    print_usage
+    exit 1;
+fi
+
+if [ ! -d "apps/$1" ]; then
+    echo "App directory '$1' not found.";
     exit 1;
 fi
 
